export type ServiceRegion = {
  id: string;
  name: string;
  description: string;
  cities: string[];
};

export const SERVICE_AREA_INTRO =
  "Airmets provides FAA Part 107–compliant drone photography, aerial videography, and ground-based photography across Southern California. Flight availability depends on FAA airspace rules, local ordinances, weather, property access, and permits for each location.";

export const SERVICE_REGIONS: ServiceRegion[] = [
  {
    id: "los-angeles-county",
    name: "Los Angeles County",
    description:
      "Urban corridors, hillside estates, coastal properties, and commercial campuses throughout greater Los Angeles.",
    cities: [
      "Los Angeles",
      "Long Beach",
      "Glendale",
      "Pasadena",
      "Burbank",
      "Santa Monica",
      "Torrance",
      "Inglewood",
      "Pomona",
      "Lancaster",
      "Palmdale",
      "El Monte",
      "Downey",
      "West Covina",
      "Norwalk",
      "Carson",
      "Santa Clarita",
      "Hawthorne",
      "Alhambra",
      "Whittier",
      "Beverly Hills",
      "Culver City",
      "West Hollywood",
      "Malibu",
      "Manhattan Beach",
      "Hermosa Beach",
      "Redondo Beach",
      "Calabasas",
      "Diamond Bar",
      "Walnut",
    ],
  },
  {
    id: "inland-empire",
    name: "Inland Empire",
    description:
      "Master-planned communities, new construction, logistics hubs, and desert-edge listings across Riverside and San Bernardino counties.",
    cities: [
      "Riverside",
      "San Bernardino",
      "Corona",
      "Moreno Valley",
      "Rancho Cucamonga",
      "Ontario",
      "Fontana",
      "Temecula",
      "Murrieta",
      "Victorville",
      "Rialto",
      "Hemet",
      "Menifee",
      "Chino",
      "Chino Hills",
      "Upland",
      "Redlands",
      "Highland",
      "Lake Elsinore",
      "Perris",
      "Eastvale",
      "Jurupa Valley",
      "Yorba Linda",
      "Brea",
      "San Dimas",
      "Claremont",
      "La Verne",
    ],
  },
  {
    id: "orange-county",
    name: "Orange County",
    description:
      "Coastal luxury homes, master-planned neighborhoods, retail centers, and hospitality properties from the coast to South County.",
    cities: [
      "Irvine",
      "Anaheim",
      "Santa Ana",
      "Huntington Beach",
      "Costa Mesa",
      "Newport Beach",
      "Laguna Beach",
      "Fullerton",
      "Orange",
      "Mission Viejo",
      "Tustin",
      "Lake Forest",
      "San Clemente",
      "Dana Point",
      "Aliso Viejo",
      "Laguna Niguel",
      "San Juan Capistrano",
    ],
  },
  {
    id: "san-diego-county",
    name: "San Diego County",
    description:
      "Coastal developments, hillside communities, commercial districts, and resort properties across the San Diego region.",
    cities: [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Encinitas",
      "La Mesa",
      "Poway",
      "Coronado",
      "Del Mar",
      "National City",
    ],
  },
  {
    id: "ventura-county",
    name: "Ventura County",
    description:
      "Agricultural land, hillside estates, coastal bluffs, and commercial properties along the Ventura County coast and valleys.",
    cities: [
      "Oxnard",
      "Ventura",
      "Thousand Oaks",
      "Simi Valley",
      "Camarillo",
      "Moorpark",
      "Santa Paula",
      "Fillmore",
      "Port Hueneme",
    ],
  },
  {
    id: "coachella-valley",
    name: "Coachella Valley & High Desert",
    description:
      "Desert modern architecture, resort communities, golf estates, and open-land projects from Palm Springs through Joshua Tree.",
    cities: [
      "Palm Springs",
      "Palm Desert",
      "Indio",
      "Coachella",
      "La Quinta",
      "Cathedral City",
      "Rancho Mirage",
      "Desert Hot Springs",
      "Joshua Tree",
      "Yucca Valley",
      "Twentynine Palms",
      "Apple Valley",
      "Hesperia",
    ],
  },
  {
    id: "central-coast",
    name: "Central Coast",
    description:
      "Wine country, coastal highways, hospitality properties, and event venues along the southern Central Coast.",
    cities: [
      "Santa Barbara",
      "Goleta",
      "Carpinteria",
      "San Luis Obispo",
      "Pismo Beach",
      "Arroyo Grande",
      "Santa Maria",
    ],
  },
];

export const ALL_SERVICE_CITIES = [...new Set(SERVICE_REGIONS.flatMap((region) => region.cities))];